#!/bin/bash

#
# Cerdo - Manages your SID's
#

# You need curses and curses::ui for perl

mkdir -p /var/lib/cerdo/rules
mkdir -p /var/lib/cerdo/logs
mkdir -p /var/lib/cerdo/state

# Place your VRT or ET rules in /var/lib/cerdo/rules
# /var/lib/cerdo/logs is for:
# error logs, user logging, rule updates,
# adding and deleting stuff ++



